// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: nodehub/client.proto

package nh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 客户端上行消息
// 请求会被网关转换为grpc请求转发到内部服务
type Request struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          uint32                 `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_ServiceCode int32                  `protobuf:"varint,2,opt,name=service_code,json=serviceCode,proto3"`
	xxx_hidden_Method      string                 `protobuf:"bytes,3,opt,name=method,proto3"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,4,opt,name=data,proto3"`
	xxx_hidden_NodeId      string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3"`
	xxx_hidden_NoReply     bool                   `protobuf:"varint,6,opt,name=no_reply,json=noReply,proto3"`
	xxx_hidden_Stream      string                 `protobuf:"bytes,7,opt,name=stream,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_nodehub_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_nodehub_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Request) GetId() uint32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *Request) GetServiceCode() int32 {
	if x != nil {
		return x.xxx_hidden_ServiceCode
	}
	return 0
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return ""
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Request) GetNodeId() string {
	if x != nil {
		return x.xxx_hidden_NodeId
	}
	return ""
}

func (x *Request) GetNoReply() bool {
	if x != nil {
		return x.xxx_hidden_NoReply
	}
	return false
}

func (x *Request) GetStream() string {
	if x != nil {
		return x.xxx_hidden_Stream
	}
	return ""
}

func (x *Request) SetId(v uint32) {
	x.xxx_hidden_Id = v
}

func (x *Request) SetServiceCode(v int32) {
	x.xxx_hidden_ServiceCode = v
}

func (x *Request) SetMethod(v string) {
	x.xxx_hidden_Method = v
}

func (x *Request) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *Request) SetNodeId(v string) {
	x.xxx_hidden_NodeId = v
}

func (x *Request) SetNoReply(v bool) {
	x.xxx_hidden_NoReply = v
}

func (x *Request) SetStream(v string) {
	x.xxx_hidden_Stream = v
}

type Request_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// id应该按照发送顺序自增长
	// 网关会在每个request对应的reply.request_id内原样返回这个值
	Id uint32
	// 服务ID，对应内部节点的每种grpc服务
	// 内部节点在注册服务发现时，会将服务ID注册到etcd中
	// 网关根据service字段将请求转发到对应的内部服务
	ServiceCode int32
	// grpc方法名，大小写敏感，例如: SayHello
	Method string
	// grpc方法对应的protobuf message序列化之后的数据
	// 具体对应关系需要自行查看grpc服务的protobuf文件
	Data []byte
	// 节点ID
	// 如果有值，网关会把本次请求直接转发到指定的节点
	// 仅仅在有状态服务的allocation配置为client时有效
	NodeId string
	// 是否需要网关返回response
	NoReply bool
	// 如果不设置值，网关会以并发的方式处理这个请求
	// 如果设置了值，网关会严格按照接收顺序处理同一个流的所有的请求
	// 使用了流以后，性能会受到一定影响，因为网关会等待上一个请求的返回之后才会处理下一个请求
	// 不同客户端以及不同的流之间不会互相影响
	// 例如：stream = "stream1"，表示这个请求属于stream1这个流
	Stream string
}

func (b0 Request_builder) Build() *Request {
	m0 := &Request{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_ServiceCode = b.ServiceCode
	x.xxx_hidden_Method = b.Method
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_NodeId = b.NodeId
	x.xxx_hidden_NoReply = b.NoReply
	x.xxx_hidden_Stream = b.Stream
	return m0
}

// 来自服务器端下行的消息
type Reply struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RequestId   uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3"`
	xxx_hidden_ServiceCode int32                  `protobuf:"varint,2,opt,name=service_code,json=serviceCode,proto3"`
	xxx_hidden_Code        int32                  `protobuf:"varint,3,opt,name=code,proto3"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,4,opt,name=data,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_nodehub_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_nodehub_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Reply) GetRequestId() uint32 {
	if x != nil {
		return x.xxx_hidden_RequestId
	}
	return 0
}

func (x *Reply) GetServiceCode() int32 {
	if x != nil {
		return x.xxx_hidden_ServiceCode
	}
	return 0
}

func (x *Reply) GetCode() int32 {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return 0
}

func (x *Reply) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Reply) SetRequestId(v uint32) {
	x.xxx_hidden_RequestId = v
}

func (x *Reply) SetServiceCode(v int32) {
	x.xxx_hidden_ServiceCode = v
}

func (x *Reply) SetCode(v int32) {
	x.xxx_hidden_Code = v
}

func (x *Reply) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

type Reply_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// 触发此次请求的request_id
	// 网关会自动给这个字段赋值
	// 如果是服务器端主动下发，request_id = 0
	RequestId uint32
	// 服务ID，对应内部节点的每种grpc服务
	// 标识这个消息来自于哪个内部服务
	// grpc调用返回结果，网关会自动给这个字段赋值
	// 如果是服务器端主动下发，需要自行赋值
	// service_code = 0，表示这个消息来自于网关本身
	ServiceCode int32
	// 消息类型代码
	// code = 0，表示这是google.protobuf.Empty类型的空消息
	Code int32
	// 下行protobuf message序列化之后的数据
	// 客户端需要根据code字段判断具体反序列化成哪个protobuf message
	Data []byte
}

func (b0 Reply_builder) Build() *Reply {
	m0 := &Reply{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RequestId = b.RequestId
	x.xxx_hidden_ServiceCode = b.ServiceCode
	x.xxx_hidden_Code = b.Code
	x.xxx_hidden_Data = b.Data
	return m0
}

var File_nodehub_client_proto protoreflect.FileDescriptor

var file_nodehub_client_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x6e, 0x6f, 0x64, 0x65, 0x68, 0x75, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x68, 0x75, 0x62, 0x22,
	0xb4, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6e, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x71, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x6f, 0x79, 0x70, 0x61, 0x72, 0x74, 0x79,
	0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x68, 0x75, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e,
	0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_nodehub_client_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nodehub_client_proto_goTypes = []any{
	(*Request)(nil), // 0: nodehub.Request
	(*Reply)(nil),   // 1: nodehub.Reply
}
var file_nodehub_client_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodehub_client_proto_init() }
func file_nodehub_client_proto_init() {
	if File_nodehub_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodehub_client_proto_rawDesc), len(file_nodehub_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nodehub_client_proto_goTypes,
		DependencyIndexes: file_nodehub_client_proto_depIdxs,
		MessageInfos:      file_nodehub_client_proto_msgTypes,
	}.Build()
	File_nodehub_client_proto = out.File
	file_nodehub_client_proto_goTypes = nil
	file_nodehub_client_proto_depIdxs = nil
}
