services:
  etcd1:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=infra0
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=nodehub-etcd-cluster
      - ETCD_INITIAL_CLUSTER=infra0=http://etcd1:2380,infra1=http://etcd2:2380,infra2=http://etcd3:2380
    ports:
      - 127.0.0.1:2379:2379
  etcd2:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=infra1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=nodehub-etcd-cluster
      - ETCD_INITIAL_CLUSTER=infra0=http://etcd1:2380,infra1=http://etcd2:2380,infra2=http://etcd3:2380
    ports:
      - 127.0.0.1:2479:2379
  etcd3:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=infra2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=nodehub-etcd-cluster
      - ETCD_INITIAL_CLUSTER=infra0=http://etcd1:2380,infra1=http://etcd2:2380,infra2=http://etcd3:2380
    ports:
      - 127.0.0.1:2579:2379
  nats1:
    image: 'bitnami/nats:latest'
    environment:
      - NATS_ENABLE_CLUSTER=yes
      - NATS_CLUSTER_PORT_NUMBER=4248
      - NATS_EXTRA_ARGS=--cluster_name=nodehub
    ports:
      - '127.0.0.1:4222:4222'
  nats2:
    image: 'bitnami/nats:latest'
    environment:
      - NATS_ENABLE_CLUSTER=yes
      - NATS_CLUSTER_PORT_NUMBER=5248
      - NATS_CLUSTER_ROUTES=nats://nats1:4248
      - NATS_EXTRA_ARGS=--cluster_name=nodehub
    ports:
      - '127.0.0.1:5222:4222'
    depends_on:
      - nats1
  nats3:
    image: 'bitnami/nats:latest'
    environment:
      - NATS_ENABLE_CLUSTER=yes
      - NATS_CLUSTER_PORT_NUMBER=6248
      - NATS_CLUSTER_ROUTES=nats://nats1:4248
      - NATS_EXTRA_ARGS=--cluster_name=nodehub
    ports:
      - '127.0.0.1:6222:4222'
    depends_on:
      - nats1
