// Code generated by protoc-gen-go-nodehub. DO NOT EDIT.
// source: auth/message.proto

package authpb

import (
	nh "github.com/joyparty/nodehub/proto/nh"
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

func init() {
	nh.RegisterReplyMessage(1, 1, reflect.TypeOf(AuthorizeAck{}))
}

func PackAuthorizeAck(msg *AuthorizeAck) (*nh.Reply, error) {
	data, err := proto.Marshal(msg)
	if err != nil {
		return nil, err
	}

	return &nh.Reply{
		ServiceCode: 1,
		Code:        1,
		Data:        data,
	}, nil
}
