// Code generated by protoc-gen-go-nodehub. DO NOT EDIT.
// source: auth/message.proto

package authpb

import (
	nh "github.com/joyparty/nodehub/proto/nh"
	proto "google.golang.org/protobuf/proto"
	reflect "reflect"
)

func PackAuthorizeAck(msg *AuthorizeAck) (*nh.Reply, error) {
	data, err := proto.Marshal(msg)
	if err != nil {
		return nil, err
	}

	return &nh.Reply{
		ServiceCode: 1,
		Code:        1,
		Data:        data,
	}, nil
}

// ReplyMessages 所有的返回值类型及其编码 [2]int32{service_code, reply_code}
var ReplyMessages = map[[2]int32]reflect.Type{
	{1, 1}: reflect.TypeOf(AuthorizeAck{}),
}
