// Code generated by protoc-gen-go-nodehub. DO NOT EDIT.
// source: room/service.proto

package roompb

// Room_ReplyCodes 每个grpc方法返回值对应的nodehub.Reply.code
var Room_ReplyCodes = map[string]int32{
	"/room.Room/Join": 1,
}
