// Code generated by protoc-gen-go-nodehub. DO NOT EDIT.
// source: echo/service.proto

package echopb

// Echo_ReplyCodes 每个grpc方法返回值对应的nodehub.Reply.code
var Echo_ReplyCodes = map[string]int32{
	"/echo.Echo/Send": 1,
}
